### ISSUE TITLE
ERROR in ./src/index.js Module not found: Error: Can't resolve 'admin-lte/bootstrap/css/bootstrap.min.css'

### ISSUE THREAD

**Issue by lc3t35** [falmar/react-adm-lte-demo#1]
When I run npm run-script build or npm test, I have this message 
````
ERROR in ./src/index.js
Module not found: Error: Can't resolve 'admin-lte/bootstrap/css/bootstrap.min.css' in '/###/react-adm-lte-demo/src'
 @ ./src/index.js 9:0-51
````
No such file in react-adm-lte repo ;)
Temporary fix by downloading [bootstrap](https://github.com/twbs/bootstrap/releases/download/v3.3.7/bootstrap-3.3.7-dist.zip), move in src, rename as bootstrap and changing import to './bootstrap/css/bootstrap.min.css'

**Comment by falmar** [comment]
Hello, thanks for reporting the issue, it have been fixed 3cc42cf90453039d4ffa1360aca53cd675af3159 Long time I don't change this repo I will probably retake it and complete all components from `react-adm-lte` and update to the newest version of `admin-lte`

The issue was caused by the new version of `admin-lte` does not include bootstrap anymore on their npm package, using `admin-lte` version `2.3.11` will solve the issue

Please update this package in order to get new components from `react-adm-lte` as well
